package modules.trafficloadbalancingmock.adapters.services

import modules.trafficloadbalancingmock.adapters.services.interfaces.TrafficLoadBalancingService

class TrafficLoadBalancingServiceImpl extends TrafficLoadBalancingService {}
